require 'travis/yml/schema/json/group'
require 'travis/yml/schema/json/map'
require 'travis/yml/schema/json/ref'
require 'travis/yml/schema/json/seq'
require 'travis/yml/schema/json/scalar'
require 'travis/yml/schema/json/schema'
