require 'travis/yml/docs/examples/bool'
require 'travis/yml/docs/examples/group'
require 'travis/yml/docs/examples/map'
require 'travis/yml/docs/examples/num'
require 'travis/yml/docs/examples/ref'
require 'travis/yml/docs/examples/secure'
require 'travis/yml/docs/examples/seq'
require 'travis/yml/docs/examples/str'
