require 'travis/yml/docs/examples'
require 'travis/yml/docs/schema/any'
require 'travis/yml/docs/schema/factory'
require 'travis/yml/docs/schema/map'
require 'travis/yml/docs/schema/scalar'
require 'travis/yml/docs/schema/secure'
require 'travis/yml/docs/schema/seq'
