#!/bin/bash

ids=$@

for id in $@; do
  # id=$(psql travis_yaml -c "select repo_id from requests where id = $id" | tail -n 3 | head -n 1 | sed 's/ //g')
  slug=$(curl -s https://api.travis-ci.org/repos/$id | jq '.slug' | sed 's/"//g')
  open "https://travis-ci.org/$slug"
done

